### ISSUE TITLE
Boken link to yaml file

### ISSUE THREAD

**Issue by JayD3211** [Azure/Copilot-For-Security#104]
The link to the Sentinel Daily Operations Sample yaml file is broken, returning 404.

This is the broken link:
[KQL_SentinelDailyOperationsSample.yaml](https://github.com/Azure/Copilot-For-Security/blob/main/Plugins/Community%20Based%20Plugins/SentinelDailyOperations/KQL_SentinelDailyOperationsSample.yml)
is broken

Here is the parent page with the link:
[Copilot-For-Security/Plugins/Community Based Plugins/Microsoft Sentinel Custom Plugin Scenarios/SentinelDailyOperations at main · Azure/Copilot-For-Security · GitHub](https://github.com/Azure/Copilot-For-Security/tree/main/Plugins/Community%20Based%20Plugins/Microsoft%20Sentinel%20Custom%20Plugin%20Scenarios/SentinelDailyOperations)

**Comment by azurekid** [comment]
I have updated the README.md to reference to the correct location for the sample file

**Comment by KwachSean** [comment]
noted , is being fixed with PR
