### ISSUE TITLE
HIBP Plugin - Plugin not loading

### ISSUE THREAD

**Issue by DavidvanWyk-DSY** [Azure/Copilot-For-Security#116]
The HIBP plugin is not loading when trying to import into Copilot for Security ([Plugins/Community Based Plugins/HaveIBeenPwned](https://github.com/Azure/Copilot-For-Security/tree/ec3e7051d8f57c34ec6e66d3e2b1187bec3ce513/Plugins/Community%20Based%20Plugins/HaveIBeenPwned))

This is the error received when trying to load it: 

2006: API skill load failed : Failed to load OpenAPI manifest from https://raw.githubusercontent.com/Azure/Copilot-For-Security/main/Plugins/Community Based Plugins/HaveIBeenPwned/OpenAPI/hibp-openapi.yaml. (Lin: 53, Col: 6, Chr: 1445) - (Lin: 53, Col: 13, Chr: 1452): Duplicate key. For more info, please check - https://aka.ms/CopilotforSecurityPluginTroubleshoot 

This happens when trying via Link and via Upload. 

Looks like an error in the openapi specfile.

**Comment by KwachSean** [comment]
thanks for your submission of the issue @DavidvanWyk-DSY  , we will review and revert
