### ISSUE TITLE
Problems when running LogicApp: SecurityCopilot-SOCshift-reporting-transfer

### ISSUE THREAD

**Issue by nlaursendk** [Azure/Copilot-For-Security#124]
There seems to be an error with the Incident split

![image](https://github.com/user-attachments/assets/bac256b3-0398-4667-b5c4-d2c2724f0695)

**Comment by KwachSean** [comment]
new update has been published https://github.com/Azure/Copilot-For-Security/tree/main/Logic%20Apps/SecurityCopilot-SOCshift-reporting-transfer
